### ISSUE TITLE
Cheddar farm - NFT displayed incorrectly

### ISSUE THREAD

**Issue by Calcifer1001** [alpha-fi/cheddar-ui-v1#1]
When opening stake/unstake on cheddar p4 farm, NFT's are displayed incorrectly:

![image](https://user-images.githubusercontent.com/83971551/208908353-4c27648f-bd1e-4d6e-9829-cbfe1c7f52e3.png)

**Comment by Megha-Dev-19** [comment]
It's been fixed, Thanks for reporting.
